INSERT INTO ALUMNOS (ID, NOMBRE, APELLIDO, EDAD, CLASE)
VALUES ((NEXT VALUE FOR ID_SEQUENCE), 'Pepe', 'López', 15, '1A');

INSERT INTO ALUMNOS (ID, NOMBRE, APELLIDO, EDAD, CLASE)
VALUES ((NEXT VALUE FOR ID_SEQUENCE), 'Manué', 'Zaragoza', 16, '1B');