-- Eliminar secuencia si existe (opcional, útil en desarrollo)
DROP SEQUENCE IF EXISTS ESCUELADB.CLASE_ID_SEQUENCE;

-- Crear secuencia para la tabla CLASE
CREATE SEQUENCE ESCUELADB.CLASE_ID_SEQUENCE
    START WITH 1
    INCREMENT BY 1;

-- CREAR TABLA CLASE
CREATE TABLE ESCUELADB.CLASE (
    ID        BIGINT       NOT NULL,
    NOMBRE    VARCHAR(100) NOT NULL UNIQUE,
    PROFESOR  VARCHAR(100) NULL,
    PRIMARY KEY (ID)
);

-- AÑADIR COLUMNA CLASE_ID (permite NULL temporalmente)
ALTER TABLE ESCUELADB.ALUMNOS
    ADD COLUMN CLASE_ID BIGINT;