INSERT INTO ESCUELADB.CLASE (ID, NOMBRE, PROFESOR)
SELECT
    NEXT VALUE FOR ESCUELADB.CLASE_ID_SEQUENCE,
    NOMBRE,
    NULL
FROM (
    SELECT DISTINCT TRIM(UPPER(CLASE)) AS NOMBRE
    FROM ESCUELADB.ALUMNOS
    WHERE CLASE IS NOT NULL AND TRIM(CLASE) <> ''
    );



